# Generated by Django 5.0.2 on 2025-07-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_customuser_last_login_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
