# Generated by Django 5.0.2 on 2025-07-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0004_alter_customuser_id_chatrooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatrooms',
            name='last_message',
        ),
        migrations.RemoveField(
            model_name='chatrooms',
            name='last_updated',
        ),
        migrations.AlterField(
            model_name='chatrooms',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chats',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
