# Generated by Django 5.0.2 on 2025-07-20 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0005_remove_chatrooms_last_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chats',
            name='timestamp',
        ),
    ]
