# Generated by Django 5.0.2 on 2025-08-14 21:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0006_remove_chats_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
