# Generated by Django 5.0.2 on 2025-08-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0007_chats_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
