# Generated by Django 5.0.2 on 2025-08-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0008_chats_notification_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
