# Generated by Django 5.0.2 on 2025-07-13 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chats',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
